name: K-Pop Database Sync

on:
  workflow_dispatch:
    inputs:
      DEBUG:
        description: "Log level"
        required: false
        type: choice
        default: "info"
        options:
          - "debug"
          - "info"
          - "warn"
          - "error"
  schedule:
    # midnight every monday is 3 pm UTC on Sunday
    - cron: "0 15 * * 0"
permissions:
  # Allowed to commit changes back to the repo
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install all dependencies (pnpm)
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true
      # This is to be converted to the new CSV files to avoid expensive mysql to sqlite conversions
      # - name: Run mysql2db script & create new DB
      #   run: pnpm tsx ./scripts/mysql2db.ts
      #   env:
      #     SORIDATA_KEY: ${{ secrets.SORIDATA_KEY }}
      #     SORIDATA_CONTACT: ${{ secrets.SORIDATA_CONTACT }}
      # - name: Commit new DB (triggers labeler update)
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     # Add only the file intended to be changed
      #     # Note on add: this is a YAML string inside a strig
      #     # See: https://github.com/marketplace/actions/add-commit#array-inputs
      #     add: |
      #       - db/kpop.db
      #     message: "chore: Syncs latest Soridata information"
      #     default_author: github_actions
